### ISSUE TITLE
Crash when looking up uses for items in nei

### ISSUE THREAD

**Issue by dozingpip** [DoubleDoorDevelopment/CrayCrafting#1]
Forge version: 10.13.0.1208
I'm also using NEI 1.0.3.51, NEIAddons 1.12.1.7, and NEIPlugins 1.1.0.7-unofficial, if those make a difference.
crash log: http://paste.ee/p/cE7YE
Tried it on a vanilla log multiple times and it crashed every time.

**Comment by Claycorp** [comment]
Theres no crash in that paste of yours.
Can you paste the crashlog instead?

**Comment by dozingpip** [comment]
Eh?  I uploaded it from multimc right after I crashed... will try again :(

**Comment by dozingpip** [comment]
Guess multimc doesn't upload the whole log? tried it again, it did the same thing... well I guess I'll copy it over to pastebin with everything this time (hopefully): http://pastebin.com/TEePpkGJ.  This one has the crash.  I checked.

**Comment by dries007** [comment]
So, I can't replicate this....

**Comment by dozingpip** [comment]
Same nei/ addons/ plugins versions?

**Comment by dozingpip** [comment]
So I just updated this mod to 1.3.0.13 from .11 and this crash still happens...  I'm trying it minus most of the other mods (76 total) I'm using to see what happens.

**Comment by dozingpip** [comment]
I'm a little confused now... I started with the mods I mentioned at the start and nothing else, added on till my entire modlist was in and no crash.  I used the same world to test it every time, so I was like cool it works now, let me make a new world and play on this working instance instead!  _Creates new world_.  _looks at uses for oak log_. _crashes_. _sadness_.

**Comment by dries007** [comment]
so does it crash when you reload the world (after restarting the client completely)

**Comment by dozingpip** [comment]
The one I just made? Yes.  The one that started with less mods? No.

**Comment by dries007** [comment]
wtf...

2014-08-24 20:32 GMT+02:00 freestraws notifications@github.com:

**Comment by dozingpip** [comment]
This is going to be annoying but I'm thinking I have to start again from nei, its addons and required files, craycrafting and d3 core, then add mods, creating a new world for each addition, until it crashes again.

**Comment by dozingpip** [comment]
I'm kinda sure that I've tracked it down to be binnie's mods... as in it doesn't crash when I have the above + forestry, does crash when I add binnie-mods-2.0-dev3.jar after creating a new world for each try.

**Comment by dozingpip** [comment]
Think I should report this in binnie's issue tracker too, then?

**Comment by dries007** [comment]
So its just binnie's mods? have you readded all other mods?

**Comment by dozingpip** [comment]
I think there might be another causing issues too, trying to figure it out now... it did crash when I created a new world and looked up usage for an item without binnie's mods in.  
Edt: It _might_ be tinker's construct as well (not sure yet b/c it could be iguanatweaks or TiCtooltips or maybe Mantle).
Edit2: definitely Tinker's Construct and binnie's mods... I should probably test to see if there are anymore.  No idea what those 2 might have in common though.

**Comment by dozingpip** [comment]
Magic bees is a 3rd.  And last.
