### ISSUE TITLE
Blacklisting items

### ISSUE THREAD

**Issue by benrobson** [DoubleDoorDevelopment/CrayCrafting#11]
Is there a way to disable the creative items in CrayCrafting? Can I use the blacklist part of the config?

craycrafting {
    # The black/whitelist. See listType.
    I:list <
     >

    # True means that the list is a whitelist. Craycrafting only applies in the dimensions in the list.
    # False means that the list is a blacklist. Craycrafting applies in all dimensions except the ones in the list [default: false]
    B:listType=false

**Comment by dries007** [comment]
No, it's for dimensions only. You cannot blacklist items.
