### ISSUE TITLE
Crashing While Loading Mod!...

### ISSUE THREAD

**Issue by LemonBoomarang81** [DoubleDoorDevelopment/CrayCrafting#13]
Emm... 
Every time I try loading the mod, it works fine, until I take something and put it in my crafting bench, the game crashes. 
I only have Ender IO, Iron-Chest, Morph Mod, Too many Items, (Which Does not even work,) And Veinminer, which also does not even work!
Helppp!!!

**Comment by Claycorp** [comment]
Log?

**Comment by LemonBoomarang81** [comment]
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events

**Comment by Claycorp** [comment]
That is not a log.

**Comment by LemonBoomarang81** [comment]
I have no idea what that is...

**Comment by Claycorp** [comment]
Do you know what a crashlog is? If not its the files inside the crash-LOGs folder, or you could send the latest file inside the LOGs folder. Either one would be a good step in giving useful information. Please don't copy paste it into the text box either, Post it on a text hosting site like pastebin or gist.

If you can't provide a log I can't help.

**Comment by LemonBoomarang81** [comment]
[2017-05-24-1.log.gz](https://github.com/DoubleDoorDevelopment/CrayCrafting/files/1113655/2017-05-24-1.log.gz)

**Comment by LemonBoomarang81** [comment]
[2017-06-29-7.log.gz](https://github.com/DoubleDoorDevelopment/CrayCrafting/files/1113658/2017-06-29-7.log.gz)
Sorry Wrong one!
xD

**Comment by Claycorp** [comment]
TMI doesn't work because its broken. Use NEI instead.
Not sure whats going on with craycrafting and the only person who does won't be around till Monday.
If you have so few mods try taking them out till it works. If it never works re-download the mod.

**Comment by LemonBoomarang81** [comment]
Okay thanks!
xD
