### ISSUE TITLE
Having a problem crafting an item

### ISSUE THREAD

**Issue by benrobson** [DoubleDoorDevelopment/CrayCrafting#15]
https://pastebin.com/VYBs2KkC

**Comment by Claycorp** [comment]
1. Nothing we can do about it. Its a side effect of messing with recipes and using NEI.
2. You are using something other than Forge to run the server. This could cause all sorts of issues when messing with recipes like this.
3. This mod isn't supported anymore. There is a possibility for an update in the future but that's not guaranteed.
