### ISSUE TITLE
CrayCrafting doesn't rotate recipes

### ISSUE THREAD

**Issue by ghost** [DoubleDoorDevelopment/CrayCrafting#16]
CrayCrafting doesn't rotate recipes, it stays the same and doesn't change the whole time i play
can someone please help?

**Comment by Claycorp** [comment]
Change the config to rotate them?

**Comment by ghost** [comment]
i can't seem to change the config what tool do you use?

**Comment by Claycorp** [comment]
Its a text file.... Like every other mod config.

**Comment by SpudsTheCyan** [comment]
I'm having the same issue, and changing the config didn't work. It still says that the recipes have been rotated in chat though. I seem to remember having this problem before and I think it was another mod causing the issue, but I'm not sure.
