### ISSUE TITLE
Cray crafting stops working

### ISSUE THREAD

**Issue by vestonion** [DoubleDoorDevelopment/CrayCrafting#17]
I will be playing a mod pack I created that has cray crafting in it and after like 30 minutes my minecraft crashes and acts like cray crafting doesn't exist. The only way i can fix it is by creating a new mod pack is there an easier fix.

**Comment by Claycorp** [comment]
Are you using 1.3.0.22?

**Comment by vestonion** [comment]
yes

**Comment by Claycorp** [comment]
¯\\\_(ツ)_/¯

We don't work on 1.7.10 anymore and this mod is a hack in the first place. All I can say is try with less mods perhaps?
