### ISSUE TITLE
not chainging recipes

### ISSUE THREAD

**Issue by krokkgeiming** [DoubleDoorDevelopment/CrayCrafting#18]
I put a 5 insten of the 0 in the script and it stil did not chaing in 5 minutes

# Configuration file

craycrafting {
    # Enable extra debug output. [default: false]
    B:debug=false

    # The black/whitelist. See listType.
    I:list <
     >

    # True means that the list is a whitelist. Craycrafting only applies in the dimensions in the list.
    # False means that the list is a blacklist. Craycrafting applies in all dimensions except the ones in the list [default: false]
    B:listType=false

    # For extra evil, this timer rotates the crafting every X minutes. 0 for disable.
    I:resetTimer=5

    # Disable sillyness only if you want to piss off the developers XD [default: true]
    B:sillyness=true

    # Message to be send to all players on timer. Empty = no message
    S:timermessage=[CrayCrafting] Recipes have been rotated!
}

**Comment by Claycorp** [comment]
¯\\\_(ツ)_/¯
This mod isn't worked on anymore, It was a hack to begin with. Sometimes it works, sometimes it doesn't. Try removing mods till it does.
