### ISSUE TITLE
Craycrafting doesn't work with other mods

### ISSUE THREAD

**Issue by JonaPjan** [DoubleDoorDevelopment/CrayCrafting#19]
Every time i put a recipe in that's not vanilla minecraft my game crashes. This is the crashreport. I hope you can help.
[crash-2019-06-10_09.49.48-client.txt](https://github.com/DoubleDoorDevelopment/CrayCrafting/files/3271079/crash-2019-06-10_09.49.48-client.txt)

**Comment by Claycorp** [comment]
Take out mods till it works, The whole mod is a hack and some things don't like it when the recipes are messed with.
