### ISSUE TITLE
Recipes not changing?

### ISSUE THREAD

**Issue by skye006** [DoubleDoorDevelopment/CrayCrafting#7]
I decided I would add Applied Energistics 2 to Dude Wheres my Block but for some reason the recipes for ae2 have not changed. Help?

**Comment by Claycorp** [comment]
AE2 has its own crafting handler. CrayCrafting only works with vanilla crafting. Any mod that makes its own crafting related stuff won't work. Blood magic infusions, Botania mana infusions, QED recipes, Most of thaumcraft, ETC...
One way to tell is by using NEI and looking at what the crafting is called on the top of the GUI. Shapeless, Shaped, Smelting, Furnace, ETC... If it's not Shaped or Shapeless then its will not work on it. If it is then there's a good chance it will work.

EDIT: Something i just thought of that MIGHT work is use minetweaker to create recipes and see if craycrafting will still cycle them. I have not tried this so it might not work at all and explode.

**Comment by skye006** [comment]
Are most of the recipes not under shaped crafting? I thought they were.  ~~I could try minetweaker and see if that works~~

EDIT: I have tried minetweaker and it does not seem to be cycling the recipes

**Comment by Claycorp** [comment]
Most of AE2 (if not all) is done through its own crafting system. It might show up as shaped/shapeless but won't work because of it going through its own system.

As the minetweaker trick doesn't work there is no way that I know of to make it work. Sorry.

**Comment by GazorBeam** [comment]
None of my recipes are changing even the vanilla recipes. The crafting recipes are different but don't cycle to a new recipe.
My config of Cray crafting
# Configuration file

craycrafting {
    # The black/whitelist. See listType.
    I:list <
     >

    # True means that the list is a whitelist. Craycrafting only applies in the dimensions in the list.
    # False means that the list is a blacklist. Craycrafting applies in all dimensions except the ones in the list [default: false]
    B:listType=false

    # For extra evil, this timer rotates the crafting every X minutes. 0 for disable.
    I:resetTimer=0

    # Message to be send to all players on timer. Empty = no message
    S:timermessage=[CrayCrafting] Recipes have been rotated!
}

What do I do?

**Comment by dries007** [comment]
This is not relevant to this issue.
