### ISSUE TITLE
Dude Where's my Blocks - Server Issues

### ISSUE THREAD

**Issue by Beastelson** [DoubleDoorDevelopment/CrayCrafting#8]
When running the mods on a server, recipes don't change. how do I fix this?

**Comment by dries007** [comment]
Do you have it on both sides?

**Comment by Beastelson** [comment]
I've copied all of the mods and configs, yes

**Comment by dries007** [comment]
Could you post a full log from the server starting please? Just drag-dop it into the comment windows on Github, the file will be uploaded here.

**Comment by dries007** [comment]
Also, did you just copy the files from a client to a server? Did you install Forge?

**Comment by Beastelson** [comment]
Installed forge first and then copied it from the client folder, yes

[fml-server-latest.txt](https://github.com/DoubleDoorDevelopment/CrayCrafting/files/1036644/fml-server-latest.txt)

**Comment by dries007** [comment]
Client log please? There seems to be nothing wrong on the server side.

**Comment by Beastelson** [comment]
I'm sorry, but I'm going to shut down my pc. I'll try and reinstall everything tomorrow and then you'll hear back from me

**Comment by dries007** [comment]
Alright
