### ISSUE TITLE
I cant get the timer to work

### ISSUE THREAD

**Issue by voodoo922** [DoubleDoorDevelopment/CrayCrafting#9]
So i have the Config file opened and all i see is a bunch of gobbledygook, I've already tried changing numbers searching videos and doing so many other things, i just need your help

**Comment by voodoo922** [comment]
here's what i see when i open it
https://pastebin.com/7mXJmgBB

**Comment by Claycorp** [comment]
Delete the file and let it regenerate.

**Comment by voodoo922** [comment]
delete CrayCrafting or the Config file?

**Comment by Claycorp** [comment]
the config.

**Comment by voodoo922** [comment]
okay i deleted it, I'm guessing if i run the modpack it will regenerate then, correct?

**Comment by Claycorp** [comment]
yes.

**Comment by voodoo922** [comment]
all done and regenerated what now?

**Comment by Claycorp** [comment]
Did it fix the file or is it still a bunch of garbage?

**Comment by voodoo922** [comment]
wait it isn't in the .jar file

**Comment by voodoo922** [comment]
im going to reinstall the mod

**Comment by Claycorp** [comment]
I don't think you know what you are doing. You should look up a guide on how to use forge and mods.

**Comment by voodoo922** [comment]
I really don't. Do you have any ones you recommend?

**Comment by Claycorp** [comment]
Nope. Almost any of them should cover the basics that you need.

**Comment by voodoo922** [comment]
i have the basics of how forge works and how to install mods, is that enough?
